"use client";
import { useRouter } from "next/navigation";
import PublicShell from "../components/PublicShell";

export default function Terms() {
  const router = useRouter();
  return (
    <PublicShell>
      <div className="max-w-3xl mx-auto py-16 px-6">
        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: January 2026</p>

        <div className="space-y-8 text-slate-300 text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account and using Qevora, you agree to these Terms of Service. If you do not agree, please do not use the service.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">2. Use of Service</h2>
            <p>Qevora provides AI-powered business readiness assessments. You agree to provide accurate information and use the service only for lawful business purposes.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">3. AI-Generated Content</h2>
            <p>Reports, scores, and recommendations are generated by AI and are provided for guidance only. They do not constitute professional, financial, or legal advice. You are responsible for decisions made based on them.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">4. Account Responsibility</h2>
            <p>You are responsible for keeping your login credentials secure and for all activity under your account.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">5. Limitation of Liability</h2>
            <p>Qevora is provided &quot;as is&quot;. We are not liable for any losses resulting from reliance on the reports or from service interruptions.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-white mb-2">6. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of Qevora after changes means you accept the updated terms.</p>
          </section>
        </div>
      </div>
    </PublicShell>
  );
} 